-- liquibase formatted sql

-- changeset kiryx:1710858662519-1
CREATE SEQUENCE IF NOT EXISTS answer_seq START WITH 1 INCREMENT BY 1;

-- changeset kiryx:1710858662519-2
CREATE SEQUENCE IF NOT EXISTS answer_vote_seq START WITH 1 INCREMENT BY 1;

-- changeset kiryx:1710858662519-3
CREATE SEQUENCE IF NOT EXISTS badge_seq START WITH 1 INCREMENT BY 1;

-- changeset kiryx:1710858662519-4
CREATE SEQUENCE IF NOT EXISTS chat_seq START WITH 1 INCREMENT BY 1;

-- changeset kiryx:1710858662519-5
CREATE SEQUENCE IF NOT EXISTS comment_seq START WITH 1 INCREMENT BY 1;

-- changeset kiryx:1710858662519-6
CREATE SEQUENCE IF NOT EXISTS ignore_tag_seq START WITH 1 INCREMENT BY 1;

-- changeset kiryx:1710858662519-7
CREATE SEQUENCE IF NOT EXISTS message_seq START WITH 1 INCREMENT BY 1;

-- changeset kiryx:1710858662519-8
CREATE SEQUENCE IF NOT EXISTS question_seq START WITH 1 INCREMENT BY 1;

-- changeset kiryx:1710858662519-9
CREATE SEQUENCE IF NOT EXISTS question_viewed_seq START WITH 1 INCREMENT BY 1;

-- changeset kiryx:1710858662519-10
CREATE SEQUENCE IF NOT EXISTS related_tag_seq START WITH 1 INCREMENT BY 1;

-- changeset kiryx:1710858662519-11
CREATE SEQUENCE IF NOT EXISTS reputation_seq START WITH 1 INCREMENT BY 1;

-- changeset kiryx:1710858662519-12
CREATE SEQUENCE IF NOT EXISTS role_seq START WITH 1 INCREMENT BY 1;

-- changeset kiryx:1710858662519-13
CREATE SEQUENCE IF NOT EXISTS tag_seq START WITH 1 INCREMENT BY 1;

-- changeset kiryx:1710858662519-14
CREATE SEQUENCE IF NOT EXISTS tracked_tag_seq START WITH 1 INCREMENT BY 1;

-- changeset kiryx:1710858662519-15
CREATE SEQUENCE IF NOT EXISTS user_badges_seq START WITH 1 INCREMENT BY 1;

-- changeset kiryx:1710858662519-16
CREATE SEQUENCE IF NOT EXISTS user_favorite_question_seq START WITH 1 INCREMENT BY 1;

-- changeset kiryx:1710858662519-17
CREATE SEQUENCE IF NOT EXISTS user_seq START WITH 1 INCREMENT BY 1;

-- changeset kiryx:1710858662519-18
CREATE SEQUENCE IF NOT EXISTS vote_question_seq START WITH 1 INCREMENT BY 1;

-- changeset kiryx:1710858662519-19
CREATE TABLE answer
(
    id                      BIGINT  NOT NULL,
    persist_date            TIMESTAMP WITHOUT TIME ZONE,
    update_date             TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    question_id             BIGINT  NOT NULL,
    user_id                 BIGINT  NOT NULL,
    html_body               TEXT    NOT NULL,
    is_helpful              BOOLEAN NOT NULL,
    is_deleted              BOOLEAN NOT NULL,
    is_deleted_by_moderator BOOLEAN NOT NULL,
    date_accept_time        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_answer PRIMARY KEY (id)
);

-- changeset kiryx:1710858662519-20
CREATE TABLE badges
(
    id                    BIGINT NOT NULL,
    badge_name            VARCHAR(255),
    reputations_for_merit INTEGER,
    description           VARCHAR(255),
    CONSTRAINT pk_badges PRIMARY KEY (id)
);

-- changeset kiryx:1710858662519-21
CREATE TABLE bookmarks
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    question_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_bookmarks PRIMARY KEY (id)
);

-- changeset kiryx:1710858662519-22
CREATE TABLE chat
(
    id           BIGINT NOT NULL,
    title        VARCHAR(255),
    persist_date TIMESTAMP WITHOUT TIME ZONE,
    chat_type    SMALLINT,
    CONSTRAINT pk_chat PRIMARY KEY (id)
);

-- changeset kiryx:1710858662519-23
CREATE TABLE comment
(
    id                  BIGINT       NOT NULL,
    text                VARCHAR(255) NOT NULL,
    comment_type        SMALLINT     NOT NULL,
    persist_date        TIMESTAMP WITHOUT TIME ZONE,
    last_redaction_date TIMESTAMP WITHOUT TIME ZONE,
    user_id             BIGINT       NOT NULL,
    CONSTRAINT pk_comment PRIMARY KEY (id)
);

-- changeset kiryx:1710858662519-24
CREATE TABLE comment_answer
(
    comment_id BIGINT NOT NULL,
    answer_id  BIGINT NOT NULL,
    CONSTRAINT pk_comment_answer PRIMARY KEY (comment_id)
);

-- changeset kiryx:1710858662519-25
CREATE TABLE comment_question
(
    comment_id  BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    CONSTRAINT pk_comment_question PRIMARY KEY (comment_id)
);

-- changeset kiryx:1710858662519-26
CREATE TABLE group_chat
(
    chat_id BIGINT NOT NULL,
    CONSTRAINT pk_group_chat PRIMARY KEY (chat_id)
);

-- changeset kiryx:1710858662519-27
CREATE TABLE groupchat_has_users
(
    chat_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_groupchat_has_users PRIMARY KEY (chat_id, user_id)
);

-- changeset kiryx:1710858662519-28
CREATE TABLE message
(
    id                  BIGINT NOT NULL,
    message             TEXT,
    last_redaction_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    persist_date        TIMESTAMP WITHOUT TIME ZONE,
    user_sender_id      BIGINT NOT NULL,
    chat_id             BIGINT NOT NULL,
    CONSTRAINT pk_message PRIMARY KEY (id)
);

-- changeset kiryx:1710858662519-29
CREATE TABLE question
(
    id                  BIGINT       NOT NULL,
    title               VARCHAR(255) NOT NULL,
    description         TEXT         NOT NULL,
    persist_date        TIMESTAMP WITHOUT TIME ZONE,
    user_id             BIGINT       NOT NULL,
    last_redaction_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    is_deleted          BOOLEAN,
    CONSTRAINT pk_question PRIMARY KEY (id)
);

-- changeset kiryx:1710858662519-30
CREATE TABLE question_has_tag
(
    question_id BIGINT NOT NULL,
    tag_id      BIGINT NOT NULL
);

-- changeset kiryx:1710858662519-31
CREATE TABLE question_viewed
(
    id           BIGINT NOT NULL,
    user_id      BIGINT,
    question_id  BIGINT,
    persist_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_question_viewed PRIMARY KEY (id)
);

-- changeset kiryx:1710858662519-32
CREATE TABLE related_tag
(
    id        BIGINT NOT NULL,
    main_tag  BIGINT NOT NULL,
    child_tag BIGINT NOT NULL,
    CONSTRAINT pk_related_tag PRIMARY KEY (id)
);

-- changeset kiryx:1710858662519-33
CREATE TABLE reputation
(
    id           BIGINT   NOT NULL,
    persist_date TIMESTAMP WITHOUT TIME ZONE,
    author_id    BIGINT   NOT NULL,
    sender_id    BIGINT,
    count        INTEGER,
    type         SMALLINT NOT NULL,
    question_id  BIGINT,
    answer_id    BIGINT,
    CONSTRAINT pk_reputation PRIMARY KEY (id)
);

-- changeset kiryx:1710858662519-34
CREATE TABLE role
(
    id   BIGINT NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_role PRIMARY KEY (id)
);

-- changeset kiryx:1710858662519-35
CREATE TABLE singel_chat
(
    chat_id     BIGINT NOT NULL,
    user_one_id BIGINT NOT NULL,
    use_two_id  BIGINT NOT NULL,
    CONSTRAINT pk_singel_chat PRIMARY KEY (chat_id)
);

-- changeset kiryx:1710858662519-36
CREATE TABLE tag
(
    id           BIGINT       NOT NULL,
    name         VARCHAR(255) NOT NULL,
    description  VARCHAR(255),
    persist_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tag PRIMARY KEY (id)
);

-- changeset kiryx:1710858662519-37
CREATE TABLE tag_ignore
(
    id             BIGINT NOT NULL,
    ignored_tag_id BIGINT NOT NULL,
    user_id        BIGINT NOT NULL,
    persist_date   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tag_ignore PRIMARY KEY (id)
);

-- changeset kiryx:1710858662519-38
CREATE TABLE tag_tracked
(
    id             BIGINT NOT NULL,
    tracked_tag_id BIGINT NOT NULL,
    user_id        BIGINT NOT NULL,
    persist_date   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tag_tracked PRIMARY KEY (id)
);

-- changeset kiryx:1710858662519-39
CREATE TABLE user_badges
(
    id        BIGINT NOT NULL,
    ready     BOOLEAN,
    user_id   BIGINT,
    badges_id BIGINT,
    CONSTRAINT pk_user_badges PRIMARY KEY (id)
);

-- changeset kiryx:1710858662519-40
CREATE TABLE user_entity
(
    id                  BIGINT NOT NULL,
    email               VARCHAR(255),
    password            VARCHAR(255),
    full_name           VARCHAR(255),
    persist_date        TIMESTAMP WITHOUT TIME ZONE,
    is_enabled          BOOLEAN,
    is_deleted          BOOLEAN,
    city                VARCHAR(255),
    link_site           VARCHAR(255),
    link_github         VARCHAR(255),
    link_vk             VARCHAR(255),
    about               VARCHAR(255),
    image_link          VARCHAR(255),
    last_redaction_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    nickname            VARCHAR(255),
    role_id             BIGINT NOT NULL,
    CONSTRAINT pk_user_entity PRIMARY KEY (id)
);

-- changeset kiryx:1710858662519-41
CREATE TABLE user_favorite_question
(
    id           BIGINT NOT NULL,
    persist_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    user_id      BIGINT NOT NULL,
    question_id  BIGINT NOT NULL,
    CONSTRAINT pk_user_favorite_question PRIMARY KEY (id)
);

-- changeset kiryx:1710858662519-42
CREATE TABLE votes_on_answers
(
    id           BIGINT NOT NULL,
    user_id      BIGINT NOT NULL,
    answer_id    BIGINT NOT NULL,
    persist_date TIMESTAMP WITHOUT TIME ZONE,
    vote_type    VARCHAR(255),
    CONSTRAINT pk_votes_on_answers PRIMARY KEY (id)
);

-- changeset kiryx:1710858662519-43
CREATE TABLE votes_on_questions
(
    id           BIGINT NOT NULL,
    user_id      BIGINT,
    question_id  BIGINT,
    persist_date TIMESTAMP WITHOUT TIME ZONE,
    vote         VARCHAR(255),
    CONSTRAINT pk_votes_on_questions PRIMARY KEY (id)
);

-- changeset kiryx:1710858662519-44
ALTER TABLE answer
    ADD CONSTRAINT FK_ANSWER_ON_QUESTION FOREIGN KEY (question_id) REFERENCES question (id);

-- changeset kiryx:1710858662519-45
ALTER TABLE answer
    ADD CONSTRAINT FK_ANSWER_ON_USER FOREIGN KEY (user_id) REFERENCES user_entity (id);

-- changeset kiryx:1710858662519-46
ALTER TABLE bookmarks
    ADD CONSTRAINT FK_BOOKMARKS_ON_QUESTION FOREIGN KEY (question_id) REFERENCES question (id);

-- changeset kiryx:1710858662519-47
ALTER TABLE bookmarks
    ADD CONSTRAINT FK_BOOKMARKS_ON_USER FOREIGN KEY (user_id) REFERENCES user_entity (id);

-- changeset kiryx:1710858662519-48
ALTER TABLE comment_answer
    ADD CONSTRAINT FK_COMMENT_ANSWER_ON_ANSWER FOREIGN KEY (answer_id) REFERENCES answer (id);

-- changeset kiryx:1710858662519-49
ALTER TABLE comment_answer
    ADD CONSTRAINT FK_COMMENT_ANSWER_ON_COMMENT FOREIGN KEY (comment_id) REFERENCES comment (id);

-- changeset kiryx:1710858662519-50
ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_USER FOREIGN KEY (user_id) REFERENCES user_entity (id);

-- changeset kiryx:1710858662519-51
ALTER TABLE comment_question
    ADD CONSTRAINT FK_COMMENT_QUESTION_ON_COMMENT FOREIGN KEY (comment_id) REFERENCES comment (id);

-- changeset kiryx:1710858662519-52
ALTER TABLE comment_question
    ADD CONSTRAINT FK_COMMENT_QUESTION_ON_QUESTION FOREIGN KEY (question_id) REFERENCES question (id);

-- changeset kiryx:1710858662519-53
ALTER TABLE group_chat
    ADD CONSTRAINT FK_GROUP_CHAT_ON_CHAT FOREIGN KEY (chat_id) REFERENCES chat (id);

-- changeset kiryx:1710858662519-54
ALTER TABLE message
    ADD CONSTRAINT FK_MESSAGE_ON_CHAT FOREIGN KEY (chat_id) REFERENCES chat (id);

-- changeset kiryx:1710858662519-55
ALTER TABLE message
    ADD CONSTRAINT FK_MESSAGE_ON_USER_SENDER FOREIGN KEY (user_sender_id) REFERENCES user_entity (id);

-- changeset kiryx:1710858662519-56
ALTER TABLE question
    ADD CONSTRAINT FK_QUESTION_ON_USER FOREIGN KEY (user_id) REFERENCES user_entity (id);

-- changeset kiryx:1710858662519-57
ALTER TABLE question_viewed
    ADD CONSTRAINT FK_QUESTION_VIEWED_ON_QUESTION FOREIGN KEY (question_id) REFERENCES question (id);

-- changeset kiryx:1710858662519-58
ALTER TABLE question_viewed
    ADD CONSTRAINT FK_QUESTION_VIEWED_ON_USER FOREIGN KEY (user_id) REFERENCES user_entity (id);

-- changeset kiryx:1710858662519-59
ALTER TABLE related_tag
    ADD CONSTRAINT FK_RELATED_TAG_ON_CHILD_TAG FOREIGN KEY (child_tag) REFERENCES tag (id);

-- changeset kiryx:1710858662519-60
ALTER TABLE related_tag
    ADD CONSTRAINT FK_RELATED_TAG_ON_MAIN_TAG FOREIGN KEY (main_tag) REFERENCES tag (id);

-- changeset kiryx:1710858662519-61
ALTER TABLE reputation
    ADD CONSTRAINT FK_REPUTATION_ON_ANSWER FOREIGN KEY (answer_id) REFERENCES answer (id);

-- changeset kiryx:1710858662519-62
ALTER TABLE reputation
    ADD CONSTRAINT FK_REPUTATION_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES user_entity (id);

-- changeset kiryx:1710858662519-63
ALTER TABLE reputation
    ADD CONSTRAINT FK_REPUTATION_ON_QUESTION FOREIGN KEY (question_id) REFERENCES question (id);

-- changeset kiryx:1710858662519-64
ALTER TABLE reputation
    ADD CONSTRAINT FK_REPUTATION_ON_SENDER FOREIGN KEY (sender_id) REFERENCES user_entity (id);

-- changeset kiryx:1710858662519-65
ALTER TABLE singel_chat
    ADD CONSTRAINT FK_SINGEL_CHAT_ON_CHAT FOREIGN KEY (chat_id) REFERENCES chat (id);

-- changeset kiryx:1710858662519-66
ALTER TABLE singel_chat
    ADD CONSTRAINT FK_SINGEL_CHAT_ON_USER_ONE FOREIGN KEY (user_one_id) REFERENCES user_entity (id);

-- changeset kiryx:1710858662519-67
ALTER TABLE singel_chat
    ADD CONSTRAINT FK_SINGEL_CHAT_ON_USE_TWO FOREIGN KEY (use_two_id) REFERENCES user_entity (id);

-- changeset kiryx:1710858662519-68
ALTER TABLE tag_ignore
    ADD CONSTRAINT FK_TAG_IGNORE_ON_IGNORED_TAG FOREIGN KEY (ignored_tag_id) REFERENCES tag (id);

-- changeset kiryx:1710858662519-69
ALTER TABLE tag_ignore
    ADD CONSTRAINT FK_TAG_IGNORE_ON_USER FOREIGN KEY (user_id) REFERENCES user_entity (id);

-- changeset kiryx:1710858662519-70
ALTER TABLE tag_tracked
    ADD CONSTRAINT FK_TAG_TRACKED_ON_TRACKED_TAG FOREIGN KEY (tracked_tag_id) REFERENCES tag (id);

-- changeset kiryx:1710858662519-71
ALTER TABLE tag_tracked
    ADD CONSTRAINT FK_TAG_TRACKED_ON_USER FOREIGN KEY (user_id) REFERENCES user_entity (id);

-- changeset kiryx:1710858662519-72
ALTER TABLE user_badges
    ADD CONSTRAINT FK_USER_BADGES_ON_BADGES FOREIGN KEY (badges_id) REFERENCES badges (id);

-- changeset kiryx:1710858662519-73
ALTER TABLE user_badges
    ADD CONSTRAINT FK_USER_BADGES_ON_USER FOREIGN KEY (user_id) REFERENCES user_entity (id);

-- changeset kiryx:1710858662519-74
ALTER TABLE user_entity
    ADD CONSTRAINT FK_USER_ENTITY_ON_ROLE FOREIGN KEY (role_id) REFERENCES role (id);

-- changeset kiryx:1710858662519-75
ALTER TABLE user_favorite_question
    ADD CONSTRAINT FK_USER_FAVORITE_QUESTION_ON_QUESTION FOREIGN KEY (question_id) REFERENCES question (id);

-- changeset kiryx:1710858662519-76
ALTER TABLE user_favorite_question
    ADD CONSTRAINT FK_USER_FAVORITE_QUESTION_ON_USER FOREIGN KEY (user_id) REFERENCES user_entity (id);

-- changeset kiryx:1710858662519-77
ALTER TABLE votes_on_answers
    ADD CONSTRAINT FK_VOTES_ON_ANSWERS_ON_ANSWER FOREIGN KEY (answer_id) REFERENCES answer (id);

-- changeset kiryx:1710858662519-78
ALTER TABLE votes_on_answers
    ADD CONSTRAINT FK_VOTES_ON_ANSWERS_ON_USER FOREIGN KEY (user_id) REFERENCES user_entity (id);

-- changeset kiryx:1710858662519-79
ALTER TABLE votes_on_questions
    ADD CONSTRAINT FK_VOTES_ON_QUESTIONS_ON_QUESTION FOREIGN KEY (question_id) REFERENCES question (id);

-- changeset kiryx:1710858662519-80
ALTER TABLE votes_on_questions
    ADD CONSTRAINT FK_VOTES_ON_QUESTIONS_ON_USER FOREIGN KEY (user_id) REFERENCES user_entity (id);

-- changeset kiryx:1710858662519-81
ALTER TABLE groupchat_has_users
    ADD CONSTRAINT fk_grohasuse_on_group_chat FOREIGN KEY (chat_id) REFERENCES group_chat (chat_id);

-- changeset kiryx:1710858662519-82
ALTER TABLE groupchat_has_users
    ADD CONSTRAINT fk_grohasuse_on_user FOREIGN KEY (user_id) REFERENCES user_entity (id);

-- changeset kiryx:1710858662519-83
ALTER TABLE question_has_tag
    ADD CONSTRAINT fk_quehastag_on_question FOREIGN KEY (question_id) REFERENCES question (id);

-- changeset kiryx:1710858662519-84
ALTER TABLE question_has_tag
    ADD CONSTRAINT fk_quehastag_on_tag FOREIGN KEY (tag_id) REFERENCES tag (id);

